version: '3.0'
services:
  mysql-db:
    # image: mysql:8.0.33
    build:
      context: .
    container_name: mysql-db
    ports:
      - '3303:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=nodeAppDB
      - MYSQL_USER=hello
      - MYSQL_PASSWORD=world
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
